version: '3.3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    build: ./web1
    ports:
      - '81:3000'
  nginx:
    image: 'nginx'
    ports:
    - '83:80'
    depends_on:
    - web1
    
